### ISSUE TITLE
Workflow for comparing two environments

### ISSUE THREAD

**Issue by joz-d7** [alex-moreno/glitcherbot#30]
Thank you for working on a non-js based regression tool. 👍 

I am having trouble diffing two different environments, I am assuming the workflow is the following:

1. Create two sample CSV files - A CSV with production URLs and the other with URLs from your development environment where they are mapped like the following in each of the CSVs:   www.production.com/test-page    www.development.com/test-page
2. Run `php bin/visual_regression_bot.php bot:crawl-sites production-site.csv`
3. Run `php bin/visual_regression_bot.php bot:crawl-sites development-site.csv`
4. Run `php bin/visual_regression_bot.php bot:compare-crawls production-site.csv development-site.csv`
5. Go to http://localhost/ and click on "changed sites"

**Comment by alex-moreno** [comment]
hey, thanks for trying this beta.

No, it's much simpler. 

1. Just use one csv with the urls you want to track. If you have sitemaps and robots.txt, all deeplinks should be tracked automatically, so no need to put anything else than the main url
2. crawl like you shown in 2. 
3. Deploy to production, or wait a few days for changes
4. crawl again like in your 2.

I need to work on the documentation a little bit more, apologies if the functionality is not 100% clear atm

**Comment by joz-d7** [comment]
Thank you for your quick response. It makes complete sense now.
