### ISSUE TITLE
Run crawler inside Docker

### ISSUE THREAD

**Issue by alex-moreno** [alex-moreno/glitcherbot#40]
At the moment Vagrant or installing the dependencies locally is the only possibility to run the crawler.

Ideally we'd have a way to run the crawler inside a Docker container, so dependencies are reduced as much as possible if you choose to use Docker instead of Vagrant.

**Comment by marcelovani** [comment]
PR https://github.com/alex-moreno/glitcherbot/pull/41

**Comment by alex-moreno** [comment]
Thanks @marcelovani , this is merged now
