### ISSUE TITLE
Sitemap crawl seems to be broken

### ISSUE THREAD

**Issue by pavlosdan** [alex-moreno/glitcherbot#47]
Unless I am misunderstanding on how to use the the sitemap crawl using the bot:crawl-xml-sitemap command is failing as follows:

execute:
php bin/visual_regression_bot.php bot:crawl-xml-sitemap sitemap.xml

fails with:
Sitemaps crawling>>>> PHP Fatal error:  Uncaught Error: Call to undefined method ScraperBot\Source\XmlSitemapSource::getCurrentIndex() in /Projects/glitcherbot/src/ScraperBot/Command/CrawlSitesCommand.php:83
Stack trace:
#0 /Projects/glitcherbot/vendor/symfony/console/Command/Command.php(256): ScraperBot\Command\CrawlSitesCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /Projects/glitcherbot/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Projects/glitcherbot/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ScraperBot\Command\CrawlXmlSitemapCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compo in /Projects/glitcherbot/src/ScraperBot/Command/CrawlSitesCommand.php on line 83

**Comment by alex-moreno** [comment]
as discussed this seems a new feature request (which I kind of like btw), so I'll close this issue and open a new one for it.

Just as a note, you cannot call the crawler using a sitemap on itself, you need to feed a csv with a list of sites, or a sites.json if you work with Acquia ACSF
