### ISSUE TITLE
Menu items not working

### ISSUE THREAD

**Issue by AshwinParmar** [alex-moreno/glitcherbot#48]
**Describe the bug**
All the routes not working after taking the latest changes from the repository. I am using Vagrant based setup.

**To Reproduce**
0. I setup VirtualHost in apache with domain name `dashboard.glitcherbot.local`

`sudo /etc/apache2/sites-available/dashboard.glitcherbot.local.conf`

```
<VirtualHost *:80>
ServerAdmin webmaster@yourdomain.com
ServerName dashboard.glitcherbot.local
ServerAlias www.dashboard.glitcherbot.local
DocumentRoot /var/www/html
DirectoryIndex index.php index.html

ErrorLog ${APACHE_LOG_DIR}/dashboard.glitcherbot.com-error.log
CustomLog ${APACHE_LOG_DIR}/dashboard.glitcherbot-access.log combined
</VirtualHost>

```
1. Apache rewrite module enabled `sudo apache2ctl -M | grep rewrite && sudo a2enmod rewrite`
2. Restart apache server `sudo systemctl restart apache2.service`
2. Go to 'http://dashboard.glitcherbot.local/ or https://192.168.33.10/'
3. Click on 'any menu item'
4. Route not working  'index.php' not working but it was already defined in 'html/.htaccess'

**Expected behavior**
It should accept index.php automatically to navigate all the menu items.

**Screenshots**
File: `src/templates/menu.twig`
Not working
`<a class="nav-link" href="/sites">Diffs</a>`

Working
`<a class="nav-link" href="/index.php/sites">Diffs</a>`

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Comment by AshwinParmar** [comment]
**Issue fixed by following changes for VirtualHost Only:**

`<VirtualHost *:80>
  ServerName dashboard.glitcherbot.local
  ServerAlias www.dashboard.glitcherbot.local
  DocumentRoot "/var/www/html"

  <Directory "/var/www/html">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/dashboard.glitcherbot.com-error.log
  CustomLog ${APACHE_LOG_DIR}/dashboard.glitcherbot-access.log combined

</VirtualHost>`

Restart apache server by executing: `sudo /etc/init.d/apache2 restart`

**Comment by AshwinParmar** [comment]
![image](https://user-images.githubusercontent.com/725230/107561424-cd86b000-6bde-11eb-8270-27c540325274.png)

IP Based issue still open.

**Comment by alex-moreno** [comment]
thanks a lot for the feedback @AshwinParmar 

The latest changes introduce some changes in the VM as well. Did you try to rebuild the vm?

Also, I'd recommend you to use Docker instead, it's much easier now to use since those latest changes.

I'll have a look soon anyway at the vm health

**Comment by alex-moreno** [comment]
I've just rebuilt using the latest version in main branch and it's all good. Please double check that you pull the changes, and potentially use bette Docker as it's the recommended method now.

Thanks a lot again
