### ISSUE TITLE
PHP Errors and Warnings

### ISSUE THREAD

**Issue by philipnorton42** [alex-moreno/glitcherbot#59]
**Describe the bug**

There are a few notices and warnings being produced by the tool when in use. For example:

    Notice: Undefined index: date1 in src/ScraperBot/Routing/Controllers/SitesController.php on line 84
    Notice: Undefined index: date2 in src/ScraperBot/Routing/Controllers/SitesController.php on line 84
    Notice: Undefined variable: persistNaughty in src/ScraperBot/Routing/Controllers/SitesController.php on line 84
    Notice: Undefined variable: persistLatest in src/ScraperBot/Routing/Controllers/SitesController.php on line 84

**To Reproduce**

Errors are produced on most pages of the site, but also when using the command line interface.

Error also produced by a missing favicon.ico file.

**Expected behavior**

No errors should be produced during the normal use of the tool.

**Comment by philipnorton42** [comment]
Added a PR for this that changes a few things in the codebase. All of the functionality is intact, I've just added some defaults to the variables being used so that they do not produce PHP warnings.

**Comment by alex-moreno** [comment]
lovely, thanks a lot @philipnorton42  💪 💪 ❤️ 

Merged
